name: firebase_image
description: A cached Flutter ImageProvider for Firebase Cloud Storage image objects.
version: 1.1.1
homepage: https://github.com/mattreid1/firebase_image

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^1.20.0
  firebase_storage: ^10.3.4
  sqflite: ^2.0.3+1
  path: ^1.8.1
  path_provider: ^2.0.11

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
